# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user/v1.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ruser/v1.proto\x12\x04\x61tes\"\x88\x01\n\x04User\x12\x10\n\x08\x66ullname\x18\x01 \x02(\t\x12\r\n\x05\x65mail\x18\x02 \x02(\t\x12\x11\n\tpublic_id\x18\x03 \x02(\t\x12\x1d\n\x04role\x18\x04 \x02(\x0e\x32\x0f.ates.User.Role\"-\n\x04Role\x12\r\n\tDEVELOPER\x10\x01\x12\t\n\x05\x41\x44MIN\x10\x02\x12\x0b\n\x07MANAGER\x10\x03')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user.v1_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USER._serialized_start=24
  _USER._serialized_end=160
  _USER_ROLE._serialized_start=115
  _USER_ROLE._serialized_end=160
# @@protoc_insertion_point(module_scope)
